FROM ubuntu:latest

# Install SSH client
RUN apt-get update && apt-get install -y openssh-client

COPY id_ed25519 /tmp/id_ed25519
COPY id_ed25519.pub /tmp/id_ed25519.pub

# Keep the container running so we can exec into it
CMD tail -f /dev/null

